### ISSUE TITLE
server.call('xxxxxx') errors out with "text.split is not a function"

### ISSUE THREAD

**Issue by bwobst** [xolvio/chimp#260] opened 2016-02-06 18:27 UTC
Meteor 1.2.1 + chimp

```
// tests/cucumber/step_definitions/steps.js
(function() {
    modules.export = function() {
        this.Given(/^I am an unauthenticated user$/, function () {
            server.call("fixtures/logout");
        });
    }
})();
```
```
// packages/fixtures/fixtures.js
Meteor.methods({
    'fixtures/logout': function() {
        Meteor.logout();
    }
});
```
```
// packages/fixtures.package.js
Package.describe({
  name: 'awesome:fixtures',
  version: '0.0.1',
  summary: '',
  debugOnly: true
});

Package.onUse(function(api) {
  api.versionsFrom('1.2.1');
  api.use('ecmascript');
  api.addFiles('fixtures.js', 'server');
});
```

The tests error out with this:
```
[chimp] Detected an unhandledRejection.
[chimp][hooks] Reason:
[chimp][hooks] text.split is not a function
```

The fixtures package has been added to my project and I've tried variations of the call like `this.server.call`, `return server.call`, `return this.server.call`.

**Comment by Sanjo** [comment] 2016-02-22 16:12
Did you find the problem?

**Comment by zvictor** [comment] 2016-04-13 08:41
I am having the same problem and it happens when the method throws a `Meteor.Error` (JS's `Error` works fine).

## code
```js
// step definition
(function() {
    modules.export = function() {
        this.Given(/^bla bla bla$/, function () {
            server.call('myMethod', 'justAnArgument');
        });
    }
})();
```

```js
// method definition
Meteor.methods({
    'myMethod': function(aParameter) {
        console.log(aParameter);
        throw new Meteor.Error('I hope you can read me on the other side...');
    }
});
```


## log
```haskell
I20160413-10:22:16.103(2)? justAnArgument
    Given bla bla bla
[chimp] Detected an unhandledRejection:
[chimp][hooks] TypeError: text.split is not a function
    at /Users/zvictor/development/network/.scripts/node_modules/meteor-promise/fiber_pool.js:33:40
```

**Comment by Sanjo** [comment] 2016-04-13 08:50
Thanks for the reproduce. I will fix it tomorrow.

**Comment by zvictor** [comment] 2016-04-13 08:55
Thanks for the quick reply. Let me know if you have a hard time trying to reproduce it.

**Comment by zvictor** [comment] 2016-04-13 09:00
And btw, I would not be surprised if we find the problem coming from Cucumber. Search for `text.split` in their own test runs:

https://travis-ci.org/cucumber/cucumber-js/jobs/100175463

**Comment by adamdawkins** [comment] 2016-04-29 15:26
Yea, I think this is happening on all errors returned within `server.call`.

**Comment by lorensr** [comment] 2016-05-08 23:13
I see this too. When I caught the error and logged it, it was `[Error: Method 'reset' not found [404]]`. It would be great if chimp printed that error instead of:

```
[chimp] Detected an unhandledRejection:
[chimp][hooks] TypeError: text.split is not a function
    at /usr/local/lib/node_modules/chimp/node_modules/cucumber/node_modules/meteor-promise/fiber_pool.js:33:40
```

**Comment by queso** [comment] 2016-05-16 02:44
Can confirm I also see this when my meteor method throws an error.

**Comment by zvictor** [comment] 2016-06-07 13:40
It seems that we are not getting any progress on this issue, even though a basic functionality of a test runner is to be able to handle thrown errors. =/

**Comment by samhatoum** [comment] 2016-06-07 14:05
Hey @zvictor 

I'll work on this today. Thank you for the reminder!

**Comment by thiagodelgado111** [comment] 2016-06-17 08:11
Same problem here calling `server.call`

**Comment by isyed867** [comment] 2016-06-22 17:28
Any updates on this?

**Comment by samhatoum** [comment] 2016-06-24 18:26
Time has been a real drag. Good news is we have a reproduce, I'll get on it as soon as time allows it. Sorry for the delays guys! 

Would also welcome the help if someone wants to roll up their sleeves.

**Comment by lgandecki** [comment] 2016-06-29 10:05
My team have also planned to fix this. :) Sorry for keeping you guys waiting. 
We've done some initial lookaround this problem, hope to have a fix soon

**Comment by lgandecki** [comment] 2016-06-29 13:14
Looks like if you comment out line 160 in  
node_modules/chimp/node_modules/xolvio-ddp/lib/ddp-client.js

https://github.com/xolvio/node-ddp-client/blob/master/lib/ddp-client.js#L160

the cucumber is able to properly parse the error object, it gets the error message from the stack. Otherwise it tries to do split on something it thinks is a text (hence text.split is not a function).

I'm not sure why the delete was happening there, I'll talk with @samhatoum and/or @Sanjo about this and should have a real solution quickly, meanwhile - if this was a show stopper please comment out that line and let us know if this is still a problem or if it caused a different one. ;)

<img width="403" alt="screen shot 2016-06-29 at 3 13 13 pm" src="https://cloud.githubusercontent.com/assets/4002543/16453142/19cd3c82-3e0c-11e6-8d86-917e779af7d8.png">

**Comment by samhatoum** [comment] 2016-06-30 12:17
maybe a quick fix is to use `.toString()` in there?

**Comment by lgandecki** [comment] 2016-07-11 14:03
This should be fixed now in the newest version of xolvio/node-ddp-client. Please run npm update in your chimp directory so the dependency gets upgraded.

**Closed by lgandecki** 2016-07-11 14:03 UTC
Labels: meteor
