### ISSUE TITLE
No testing database after migrating from xolvio:cucumber to chimp

### ISSUE THREAD

**Issue by natecox** [xolvio/chimp#195] opened 2015-12-16 07:30 UTC
I've just migrated my code base from the `xolvio:cucumber` meteor package to the standalone chimp server, and so far everything is working fine except for one major issue: the testing suite is now using my normal development database, rather than the specific testing database it was using before. 

How can I return the the functionality of having a separate testing database at this point? My test suite is dependent on the fact that I can start from a fresh database before every scenario.

**Comment by samhatoum** [comment] 2015-12-16 08:02
start separate meteor app for testing! This is what Velocity did :)

**Comment by natecox** [comment] 2015-12-16 08:09
Even if I were to start two different meteor instances, wouldn't they by default both try to use the 'meteor' database? How did `xolvio:cucumber` set the database name?

**Comment by samhatoum** [comment] 2015-12-16 08:17
ah yes, you can start the first meteor app, then pass the second app the MONGO_URL of the first app.

so something like:
`meteor`
then
`MONGO_URL=mongodb://localhost:27017/chimp_db meteor --port 3100`

**Comment by samhatoum** [comment] 2015-12-16 08:37
be sure to close this if it works for you :)

**Comment by natecox** [comment] 2015-12-16 09:12
Well, I got it working, but it's sloppy and I'm not particularly thrilled with the user experience. 

Essentially I have to start my normal server, then start a mirror with a different mongo url, then start chimp and point it at the mirror. Each of these steps is dependent on the step before it and will fail if executed concurrently, meaning I have to either run three separate terminal windows or run `sleep` commands between them.

How would you go about getting this on CI?

**Comment by samhatoum** [comment] 2015-12-16 10:00
I would write a script that does all this work. Also, you don't need to use sleep, you can wait for the Meteor message to say "app started" and then take the next step. I'll probably make a script in the next few days and make it accessible in the docs

On CI you can just run 1 instance on port 3000 since you don't need to develop

**Comment by Alino** [comment] 2015-12-16 10:30
how do you run meteor on background on CI, so you can run chimp then? I have no success with nohup

**Comment by ashersz** [comment] 2015-12-16 14:15
I could not make working my dev app on port 3000 and the chimp test on 3300 together because I have jasmine tests running with velocity. Although I added VELOCITY=0 to my chimp command line, the browser launched by chimp included the velocity frame. Most of my click failed, elements were hidden by the velocity frame.
here is my full command line file
#!/usr/bin/env bash
MONGO_URL=mongodb://db_user:pw@localhost:27017/db-cucumber \
ROOT_URL=http://localhost:3300 \
CLUSTER_SERVICE=web \
CLUSTER_DISCOVERY_URL=mongodb://db_user:pw@localhost:27017/db \
CLUSTER_PUBLIC_SERVICES=search \
CLUSTER_ENDPOINT_URL=http://localhost:3300 \
VELOCITY=0 \
JASMINE_CLIENT_UNIT=0 \
JASMINE_CLIENT_INTEGRATION=0 \
JASMINE_SERVER_UNIT=0 \
JASMINE_SERVER_INTEGRATION=0 \
meteor --port 3300 --settings ../settings.dev.json $@

**Comment by ashersz** [comment] 2015-12-16 16:32
I tried to run chimp on a linux machine where I have firefox installed
I got the following error

[tomcat@aws1ct001 cucumber]$ chimp --ddp=http://localhost:3000 --browser=firefox
[chimp] Running...

/usr/lib/node_modules/chimp/node_modules/selenium-standalone/lib/install.js:248
  fs.access(where, fs.R_OK | fs.X_OK, function(err) {
     ^
TypeError: Object #<Object> has no method 'access'
    at chmodChromeDr (/usr/lib/node_modules/chimp/node_modules/selenium-standalone/lib/install.js:248:6)
    at /usr/lib/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:699:13
    at iterate (/usr/lib/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:256:13)
    at /usr/lib/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:268:29
    at /usr/lib/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:40:16
    at /usr/lib/node_modules/chimp/node_modules/selenium-standalone/node_modules/async/lib/async.js:705:17
    at Object._onImmediate (/usr/lib/node_modules/chimp/node_modules/selenium-standalone/lib/install.js:223:5)
    at processImmediate [as _immediateCallback] (timers.js:363:15)
[tomcat@aws1ct001 cucumber]$ which firefox
/usr/bin/firefox

Seems it is trying to access a chrome driver although I asked for firefox.

**Comment by samhatoum** [comment] 2015-12-16 22:47
Good points guys, we're writing a script to make Meteor starting for Jasmine users easier. More shorlty

**Comment by Alino** [comment] 2015-12-16 23:12
regarding my question on how to run meteor as a background process on circleCI - I found out that you have to run it with ```background: true``` property in your circle.yml
more info here https://circleci.com/docs/background-process

**Comment by philcruz** [comment] 2015-12-18 22:21
+1 that a smoother process for this would be great. For now, on my Mac, I just start the app, mirror and chimp manually in 3 different terminals. Works fine. 

On Windows, I try to do the same and when I start the mirror I get
>SET IS_MIRROR=1
>SET MONGO_URL=mongodb://localhost:3001/chimp_db
> meteor run --settings config/config.local.json --port 3100
             
    [[[[[ ~\D\Cruz\projects\my-app ]]]]]              
                                                                         
    => Started proxy.                                                        
                                                                         
    C:\Users\Phil\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.win
    dows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245             
                                                throw(ex);               
                                                      ^                  
    Error: EBUSY, rmdir 'D:\Cruz\projects\my-app\.mete
    or\local\build\programs\server'                                          
      at Object.Future.wait (C:\Users\Phil\AppData\Local\.meteor\packages\met
    eor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\f
    uture.js:398:15)                                                         

Any ideas what the problem is?

**Comment by samhatoum** [comment] 2015-12-19 00:52
I'll soon release a script that makes the starting process easier.

It looks like on windows you can't start two Meteor apps at once. This is a meteor issue and should be resolved with the new `test-app` mode

**Comment by shrop** [comment] 2015-12-19 10:50
Based on some of the above info, I am starting my main meteor instance in dev as I normally do, but have an optional script that allows developers to fire up a mirror instance. Thanks to @samhatoum for this concept.

https://gist.github.com/shrop/f0fe7e74290d89081a0b

**Comment by samhatoum** [comment] 2015-12-19 17:20
Here's another script that should solve everyone's needs:

https://gist.github.com/samhatoum/d46fc75e1474aaff22d2

you can either do `chimpNoMirror()` or `chimpWithMirror()`

**Comment by samhatoum** [comment] 2015-12-19 17:22
I'll probably merge this into chimp somehow soon

**Comment by natecox** [comment] 2015-12-19 19:07
@samhatoum I've updated your script slightly to not depend on globally installed chimp, and to depend on an environment variable to start with a mirror. Using this you can include it as a part of your NPM scripts:

      "scripts": {
        "start": "WITH_MIRROR=true .scripts/chimp.js",
        ...
      },

https://gist.github.com/natecox/572e7322458d1871818a

**Comment by danimbrogno** [comment] 2015-12-23 17:41
When I naming it with the .js extension causes it to be compiled by angular-babel package which throws an error since the script begins with a #. Is it okay to just drop the .js file extension?

I'm also getting this error:
```
I20151223-12:36:06.982(-5)? Exception from task: Error: ENOENT, open '../web.browser/head.html'
I20151223-12:36:06.983(-5)?     at Object.Future.wait (/Users/danimbrogno/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
I20151223-12:36:06.983(-5)?     at meteor://💻app/packages/meteor/helpers.js:119:1
I20151223-12:36:06.983(-5)?     at readUtf8FileSync (meteor://💻app/packages/boilerplate-generator/boilerplate-generator.js:6:1)
I20151223-12:36:06.983(-5)?     at meteor://💻app/packages/boilerplate-generator/boilerplate-generator.js:81:1
I20151223-12:36:06.983(-5)?     at Array.forEach (meteor://💻app/packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
I20151223-12:36:06.983(-5)?     at Function._.each._.forEach (meteor://💻app/packages/underscore/underscore.js:105:1)
I20151223-12:36:06.983(-5)?     at [object Object].Boilerplate._generateBoilerplateFromManifestAndSource (meteor://💻app/packages/boilerplate-generator/boilerplate-generator.js:63:1)
I20151223-12:36:06.984(-5)?     at new Boilerplate (meteor://💻app/packages/boilerplate-generator/boilerplate-generator.js:16:1)
I20151223-12:36:06.984(-5)?     at Object.WebAppInternals.generateBoilerplateInstance (meteor://💻app/packages/webapp/webapp_server.js:285:1)
I20151223-12:36:06.984(-5)?     at meteor://💻app/packages/webapp/webapp_server.js:562:1
I20151223-12:36:06.984(-5)?     at Function._.each._.forEach (meteor://💻app/packages/underscore/underscore.js:113:1)
I20151223-12:36:06.984(-5)?     at meteor://💻app/packages/webapp/webapp_server.js:560:1
I20151223-12:36:06.984(-5)?     at runWithEnvironment (meteor://💻app/packages/meteor/dynamics_nodejs.js:110:1)
I20151223-12:36:06.984(-5)?     at Object.task (meteor://💻app/packages/meteor/dynamics_nodejs.js:123:1)
I20151223-12:36:06.985(-5)?     at [object Object]._.extend._run (meteor://💻app/packages/meteor/fiber_helpers.js:147:1)
I20151223-12:36:06.985(-5)?     at meteor://💻app/packages/meteor/fiber_helpers.js:125:1
I20151223-12:36:06.985(-5)?     - - - - -
W20151223-12:36:06.986(-5)? (STDERR) 
W20151223-12:36:06.986(-5)? (STDERR) /Users/danimbrogno/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
W20151223-12:36:06.986(-5)? (STDERR) 						throw(ex);
W20151223-12:36:06.986(-5)? (STDERR) 						      ^
W20151223-12:36:06.986(-5)? (STDERR) Error: ENOENT, open '../web.browser/head.html'
W20151223-12:36:06.986(-5)? (STDERR)     at Object.Future.wait (/Users/danimbrogno/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20151223-12:36:06.987(-5)? (STDERR)     at [object Object]._.extend.runTask (meteor://💻app/packages/meteor/fiber_helpers.js:81:1)
W20151223-12:36:06.987(-5)? (STDERR)     at Object.WebAppInternals.generateBoilerplate (meteor://💻app/packages/webapp/webapp_server.js:559:1)
W20151223-12:36:06.987(-5)? (STDERR)     at Object.main (meteor://💻app/packages/webapp/webapp_server.js:764:1)
W20151223-12:36:06.987(-5)? (STDERR)     at /Users/danimbrogno/Repositories/splendr/app/.meteor/local/build/programs/server/boot.js:275:27
W20151223-12:36:06.987(-5)? (STDERR)     - - - - -
W20151223-12:36:06.987(-5)? (STDERR)     at Object.Future.wait (/Users/danimbrogno/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20151223-12:36:06.987(-5)? (STDERR)     at meteor://💻app/packages/meteor/helpers.js:119:1
W20151223-12:36:06.988(-5)? (STDERR)     at readUtf8FileSync (meteor://💻app/packages/boilerplate-generator/boilerplate-generator.js:6:1)
W20151223-12:36:06.988(-5)? (STDERR)     at meteor://💻app/packages/boilerplate-generator/boilerplate-generator.js:81:1
W20151223-12:36:06.988(-5)? (STDERR)     at Array.forEach (meteor://💻app/packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
W20151223-12:36:06.988(-5)? (STDERR)     at Function._.each._.forEach (meteor://💻app/packages/underscore/underscore.js:105:1)
W20151223-12:36:06.988(-5)? (STDERR)     at [object Object].Boilerplate._generateBoilerplateFromManifestAndSource (meteor://💻app/packages/boilerplate-generator/boilerplate-generator.js:63:1)
W20151223-12:36:06.988(-5)? (STDERR)     at new Boilerplate (meteor://💻app/packages/boilerplate-generator/boilerplate-generator.js:16:1)
W20151223-12:36:06.988(-5)? (STDERR)     at Object.WebAppInternals.generateBoilerplateInstance (meteor://💻app/packages/webapp/webapp_server.js:285:1)
W20151223-12:36:06.988(-5)? (STDERR)     at meteor://💻app/packages/webapp/webapp_server.js:562:1
W20151223-12:36:06.988(-5)? (STDERR)     at Function._.each._.forEach (meteor://💻app/packages/underscore/underscore.js:113:1)
W20151223-12:36:06.988(-5)? (STDERR)     at meteor://💻app/packages/webapp/webapp_server.js:560:1
W20151223-12:36:06.989(-5)? (STDERR)     at runWithEnvironment (meteor://💻app/packages/meteor/dynamics_nodejs.js:110:1)
W20151223-12:36:06.989(-5)? (STDERR)     at Object.task (meteor://💻app/packages/meteor/dynamics_nodejs.js:123:1)
W20151223-12:36:06.989(-5)? (STDERR)     at [object Object]._.extend._run (meteor://💻app/packages/meteor/fiber_helpers.js:147:1)
W20151223-12:36:06.989(-5)? (STDERR)     at meteor://💻app/packages/meteor/fiber_helpers.js:125:1
W20151223-12:36:06.989(-5)? (STDERR)     - - - - -
=> Exited with code: 8
=> Meteor server restarted
=> Started your app.
```

Any ideas?

**Comment by samhatoum** [comment] 2015-12-28 06:13
Hey

The error `I20151223-12:36:06.982(-5)? Exception from task: Error: ENOENT, open '../web.browser/head.html'` will happen occasionally. This is a Meteor problem and will hopefully be fixed with 1.3

As for the .js script, just put it under `.scripts` and it will be ignored by meteor

**Comment by samhatoum** [comment] 2015-12-28 06:14
Please see here for 
https://github.com/xolvio/automated-testing-best-practices

**Comment by samhatoum** [comment] 2015-12-28 06:15
you can use:

`WITH_MIRROR=1 npm start`

**Closed** 2015-12-28 06:14 UTC

**Comment by yogiben** [comment] 2016-02-05 16:37
@samhatoum I'm I've looked at all the scripts, but wanted something simpler for my purposes (and to understand).

The issue is that Chimp is accessing the development db opposed to `chimp_db`.

I'm running 3 scripts

Start Meteor instance
```
meteor --settings private/settings/dev.json
```

Start Mirror instance
```
IS_MIRROR=true MONGO_URL=mongodb://localhost:3001/chimp_db \
     meteor -p 3100 --settings private/settings/dev.json
```

Start Chimp
```
chimp --path=tests --ddp=http://localhost:3100 --watch
```

**Comment by samhatoum** [comment] 2016-02-08 21:30
Cool. Are those three commands working for your setup?

**Comment by yogiben** [comment] 2016-02-09 10:09
Not as expected.

When running chimp, it is using the `meteor` database opposed to the `chimp_db` database.

**Comment by rohithb** [comment] 2016-03-10 16:44
I just added this `package.json` file in the root directory, and uses `npm test` to start chimp. So chimp will use separate test database.
```
{
  "name": "chimp-test",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "MONGO_URL=mongodb://localhost:27017/chimp_db meteor --port 3100 & chimp --ddp=http://localhost:3100  --watch --path=tests"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "chai": "^3.5.0",
    "chimp": "^0.30.0"
  }
}
```

**Comment by jirikrepl** [comment] 2016-11-22 17:18
Thanks to [this](https://github.com/meteor/meteor/issues/6532) I used `METEOR_LOCAL_DIR` env variable and started Meteor app on different port.
So my development app is running on port 3000 and chimp app on port 3100.

I am on Windows and I wrote small chimp-run batch script. You can do something similar on Linux with [nohup](https://documentation.codeship.com/classic/continuous-integration/run-a-command-in-the-background/).

    @echo off
    
    REM netstat checks if Meteor is running on port 3100. If not start it. Then start chimp tests.
    
    netstat -a -o | find "3100"
    if errorLevel 1 (
        SET METEOR_LOCAL_DIR=../second-meteor-instance
        start meteor -p 3100
    )
    chimp --ddp=http://localhost:3100 --mocha --path=chimp/tests
