### ISSUE TITLE
"pending is not defined" error

### ISSUE THREAD

**Issue by tomitrescak** [xolvio/chimp#427] opened 2016-07-21 01:08 UTC
##### Expected behaviour

Hi, I'm following the tutorial on [https://chimp.readme.io/docs/tutorial](https://chimp.readme.io/docs/tutorial). While following step by step what is requested, I'm getting an error `pending is not defined`. It looks like chimp is using old jasmine?
##### Actual behaviour

`pending is not defined`
##### Steps to reproduce the problem

Tutorial on [https://chimp.readme.io/docs/tutorial](https://chimp.readme.io/docs/tutorial).
After defining following file error is thrown:

```
module.exports = function() {

  this.Given(/^I have visited Google$/, function () {
    // Write the automation code here
    pending();
  });

  this.When(/^I search for "([^"]*)"$/, function (arg1) {
    // Write the automation code here
    pending();
  });

  this.Then(/^I see "([^"]*)"$/, function (arg1) {
    // Write the automation code here
    pending();
  });

}
```
##### Used version
- Chimp: 0.3.8 
- Node.js: 4.4.7
- Operation system: El Capitan
##### Console / Log Output

(Upload long logs to [Gist](https://gist.github.com/) and link it here)

---

_Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others._

**Comment by tahaykNSM** [comment] 2016-07-27 10:53
I'm having the same error after the last update

**Comment by tahaykNSM** [comment] 2016-07-27 14:26
I don't know what is the issue, but I rolled back to chimp 0.35.0 and it worked.
`npm install -g chimp@0.35.0`

**Comment by ryan-boder** [comment] 2016-08-27 20:40
Same issue here. I tried 0.40.4 and 0.39.4 - both had this same issue. Installed 0.35.0 and it worked.

**Comment by samhatoum** [comment] 2016-08-28 16:10
looks like we're no longer attaching the globals @lgandecki 

Lets get this prioritized, it's core cucumber functionality

**Comment by lucetius** [comment] 2016-09-06 09:32
Merged with #459

**Comment by ochemerys** [comment] 2017-01-08 20:58
the same here

chimp: 0.46.0
node: v6.9.2
OS: Win 7

Error Message:
     ReferenceError: pending is not defined
         at World.<anonymous>

**Comment by samhatoum** [comment] 2017-01-08 23:23
@ochemerys how are you running chimp?

**Comment by ochemerys** [comment] 2017-01-09 00:01
node_modules\.bin\chimp.cmd --watch

**Comment by ochemerys** [comment] 2017-01-09 00:02
`node_modules\.bin\chimp.cmd --watch`

**Comment by samhatoum** [comment] 2017-01-09 00:03
and if you run `node_modules\.bin\chimp.cmd --version` what do you see?

**Comment by ochemerys** [comment] 2017-01-09 00:04
0.46.0

**Comment by samhatoum** [comment] 2017-01-09 00:05
ok cool. can you show me the code where you're using `pending` please?

**Comment by ochemerys** [comment] 2017-01-09 00:06
```
module.exports = function() {

    this.Given(/^I have visited Google$/, function () {
        browser.url('http://google.com');
    });

    this.When(/^I search for "([^"]*)"$/, function (searchTerm) {
        browser.setValue('input[name="q"]', searchTerm);
        browser.keys(['Enter']);
    });

    this.Then(/^I see "([^"]*)"$/, function (link) {
        pending();
        //browser.waitForExist('a=' + link);
    });

}
```

**Comment by ochemerys** [comment] 2017-01-09 00:11
if I comment out pending();
and uncomment //browser.waitForExist('a=' + link);
step is completed and all is green

**Comment by samhatoum** [comment] 2017-01-09 00:25
Ok, I just checked out and this is a confirmed regression. Thanks for reporting. We'll need some tests around this to ensure it doesn't happen again

**Comment by samhatoum** [comment] 2017-01-09 00:26
@lucetius

**Closed** 2017-02-09 15:08 UTC
Labels: bug, in progress
