### ISSUE TITLE
Require wrong selenium server version

### ISSUE THREAD

**Issue by devinchen** [xolvio/chimp#184] opened 2015-12-10 04:06 UTC
When I run `chimp --browser=firefox --debug --baseUrl=http://localhost:8000` and got this error
It download 2.47.1 version of selenium but require 2.48.2, why?

```
[chimp] Running...
[chimp] interrupting
[chimp] no processes to interrupt
[chimp][selenium] Selenium object created
[chimp][selenium] Start
[chimp][selenium] Installing Selenium + drivers if needed
selenium-standalone installation [====================] 100% 0.0s

[chimp][selenium] hub can be seen at http://localhost:58018/wd/hub
[chimp] Finished running async processes with errors
[chimp] run complete with errors [Error: Missing /PROJECT_FOLDER/node_modules/chimp/node_modules/selenium-standalone/.selenium/selenium-server/2.48.2-server.jar]
```

**Comment by samhatoum** [comment] 2015-12-10 06:43
duplicate of #185

**Closed** 2015-12-10 06:43 UTC
