### ISSUE TITLE
Node.js 7 and up does not show the error when an error occurs

### ISSUE THREAD

**Issue by capaj** [xolvio/chimp#612] opened 2017-04-25 10:50 UTC
The bug can be easily reproduced here(just clone and type `npm start`):
https://github.com/capaj/chimp-cucumber-boilerplate/tree/showcase-awful-errorhandling
#####  Expected behaviour
```
[chimp] Running...
Feature: Landing

  Scenario: It works
  ✖ When When I load up "facebook.com"
  - Then I should be able to select "Jan"

Failures:

1) Scenario: It works - features/landing.feature:3
   Step: When When I load up "facebook.com" - features/landing.feature:4
   Step Definition: features/step_definitions/landing.js:2
   Message:
     Error: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot navigate to invalid URL"}
         at World.<anonymous> (features/step_definitions/landing.js:3:13)

1 scenario (1 failed)
2 steps (1 failed, 1 skipped)
0m00.067s

```

#####  Actual behaviour
```
Feature: Landing

  Scenario: It works
  ✖ When When I load up "facebook.com"
  - Then I should be able to select "Jan"

Failures:

1) Scenario: It works - features/landing.feature:3
   Step: When When I load up "facebook.com" - features/landing.feature:4
   Step Definition: features/step_definitions/landing.js:2
   Message:
     Error
         unknown error line

1 scenario (1 failed)
2 steps (1 failed, 1 skipped)
0m00.021s
Cucumber steps failed

```

##### Exact steps to reproduce / repository that demonstrates the problem
Please put long code snips in a [Gist](https://gist.github.com/) and provide a link here.

#####  Version & tools:

* Chimp: "^0.48.0"
* Node.js: 7.8.0
* Java: openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-4-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

* Operation system: ubuntu 17.04

**Comment by andrialexandrou** [comment] 2017-05-12 19:24
Upvote for this issue.

- Chimp 0.49.0
- Node 7.10.0
- Java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
- Darwin 16.5.0

**Comment by jondeaves** [comment] 2017-05-30 11:02
Also experiencing. Can use NVM to go back to 6.9.4 version of node and error shows as expected

OS: Ubuntu 16.04
Chimp: 0.49.0
Node: 7.9.0
Java: openjdk version "1.8.0_131"

**Comment by kristiankyvik** [comment] 2017-06-01 13:20
any ideas on how to fix this?

**Comment by joscha** [comment] 2017-06-21 18:02
Seeing this as well with node `7.5.0`

**Comment by tiagolr** [comment] 2017-07-06 08:52
Same here with node 8.1.3

**Comment by justgook** [comment] 2017-07-27 09:55
8.2.1 Still any ideas where is problem ?

**Comment by samhatoum** [comment] 2017-07-27 13:21
I'm looking in this now

**Comment by joscha** [comment] 2017-08-07 23:54
@samhatoum did you get anywhere with this?

**Comment by samhatoum** [comment] 2017-08-08 09:10
not yet @joscha, try me again by Saturday. Sorry for the delays, I'm swamped!

**Comment by joscha** [comment] 2017-08-18 06:04
ping @samhatoum :)

**Comment by lgandecki** [comment] 2017-08-22 16:42
<img width="1183" alt="screen shot 2017-08-22 at 20 41 49" src="https://user-images.githubusercontent.com/4002543/29576832-6096f230-877a-11e7-82f9-6d4c978b2420.png">
Got it to this .. Can't figure out how to get the file line yet, as that would be very useful. I will keep digging, at least I know where this is all coming from.

**Comment by lgandecki** [comment] 2017-08-22 16:48
ok, once I posted this, thinking I'm done for today, I had a rather obvious idea.. and got it...

<img width="1394" alt="screen shot 2017-08-22 at 20 45 28" src="https://user-images.githubusercontent.com/4002543/29577002-e87045a8-877a-11e7-9c09-917de86aecc1.png">


I will do my best to release a version with a fix tomorrow. I need to check if I'm not breaking anything in the older versions. 

This is inside cucumber v1 version btw, I'd be curious to see if this is just a universal problem with cucumber v1 (which is not really maintained anymore)

**Comment by joscha** [comment] 2017-08-22 21:57
Great work @lgandecki!

**Comment by hexsprite** [comment] 2017-08-26 01:30
@lgandecki i am using jasmine with v1 and seeing the same issue with error messages. Will your fix also address that too?

**Comment by lgandecki** [comment] 2017-08-26 05:16
Yeah, righ.... no.
That's exactly what I realized, and why havent't I pushed the fix yet. So seems like this might be coming from webdriverio (and I've fixed a similar issue in that codebase recently).
I have a few hours blocked today on that issue. Will update you guys with what I found.

**Comment by lgandecki** [comment] 2017-08-26 18:07
Alright,

I spent today digging around this, and I don't have good news :-( 

There are two issues,

**First** is caused by the change of how Errors construction is happening in node 7, basically, it used to be ok to extend error class, not pass anything to the parent constructor, and put whatever you wanted on this.type / this.message . 
https://github.com/webdriverio/webdriverio/blob/master/lib/utils/ErrorHandler.js#L5 

This is no longer the case, in the end, if you want the log of the error to have a proper message, you need to pass it to the super() (so - instead of doing this.message = "wrong url" you do const message = "wrong url" and then super(message) ). When you look at the error.message, it's still there, but it doesn't show up in the actuall error log. Not fully understanding what's going on I've recently hacked this to show errors in debug mode - https://github.com/webdriverio/webdriverio/commit/5b13166168a064adec45f8a25cb3f9d96af31544 ,  (sorry for that @christian-bromann , I will rever this and send a proper fix in the next few days). In the pictures posted above, I tried to do the same with cucumber, but then I realized, this is a bigger problem. So, with this fix in place, we will see "Error: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot navigate to invalid URL"}" instead of "Error"

### **Now, to the difficult part.** Showing the line of the error.
Basically, the issue starts with node 7.0, out of the ~1600 commits that happened between a released 6.x version, and 7.0, I was able to pinpoint the issue to here:

![screen shot 2017-08-26 at 21 37 45](https://user-images.githubusercontent.com/4002543/29743633-f6b75348-8aa6-11e7-8b6e-79cfaa9dda57.png)


With nodejs/node#8a24728 being the last "working" version, and nodejs/node#96933df being the first that compiles after the v8 5.4 update, and first not working.

The difference is in the way v8 started to showing a stack trace when running fiberized/asynced code. (it might be in the way we fiberize things in chimp, one thing to try is to see how this works with sync mode of wdio runner)
Notice, with the 5.4 update, the first line, and the only we care about is missing
![screen shot 2017-08-26 at 17 48 16](https://user-images.githubusercontent.com/4002543/29743731-81632066-8aa8-11e7-9883-19e12d9fca0c.png)

Commit before, it's there:
![screen shot 2017-08-26 at 17 47 57](https://user-images.githubusercontent.com/4002543/29743732-8672118e-8aa8-11e7-8ec7-72d83824ea01.png)

The way webdriverio neatly produces custom errors, using the this.constructor argument here: Error.captureStackTrace(this, this.constructor) 
they remove the irrelevant to the user part of the stack trace. But, without the line we care about, we are left with nothing, and that's why we see "unknown error line".

unfortunately, the commit that brought the 5.4 update is massive ( 2,386 changed files with 260,277 additions and 148,300 deletions. ) and beyond my grasp at this moment. 

Do you guys know of any nodejs magicians that could help us here? 

I think the next step will be to work on preparing a much smaller example that would show the different stack traces, while not requiring running selenium/chromedriverio and loading the whole webdriverio, or chimp, to isolate the issue. I'm a bit hooked now, so I will most probably spend some time on this during the week, but I would appreciate any help!

**Comment by rsshilli** [comment] 2018-04-25 17:56
Could we get the webdriver.io guys to help fix this?

**Comment by lgandecki** [comment] 2018-04-25 17:58
I think this is more about the way we fiberize webdriverio, not webdriverio itself.

**Comment by samhatoum** [comment] 2018-11-09 19:22
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues

**Closed by samhatoum** 2018-11-09 19:22 UTC
