### ISSUE TITLE
Chimp does nothing.

### ISSUE THREAD

**Issue by nadeemja** [xolvio/chimp#420] opened 2016-07-13 18:49 UTC
#####  Expected behaviour

Should open browser windows and run test.

#####  Actual behaviour

A lot of messages and nothing. The first time it asked my to install java, which I did. But still nothing changed.

##### Steps to reproduce the problem

I did this:

1. npm install -g chimp

2. chimp --watch --ddp=http://localhost:3000

3. Popup asks to install java. I did.

4. chimp --watch --ddp=http://localhost:3000

5. See log below.

#####  Used version

* Chimp: 0.36.1.
* Node.js: 6.3.0
* Operation system: OS X 10.11.5.

#####  Console / Log Output

https://gist.github.com/nadeemja/41bb678b1d71e6f991c4ce15f85fba69

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment] 2016-07-13 20:03
This is a known issue with node 6+, you need to downgrade node for the time being. Upgrade coming soon

**Comment by samhatoum** [comment] 2016-07-13 20:04
Duplicate of #349

**Closed by samhatoum** 2016-07-13 20:04 UTC
