### ISSUE TITLE
saveScreenshot triggers rerun with phantom js

### ISSUE THREAD

**Issue by thebarty** [xolvio/chimp#380] opened 2016-05-17 10:24 UTC
Hi guys,

when running chimp like ``chimp --ddp=http://localhost:3300 --mocha --path=tests --browser=phantomjs --watchTags="@watch" --watch;`` and using a ``browser.saveScreenshot(path)`` chimp will trigger a rerun ``[chimp] Running...`` after saving the screenshot.

I guess this is not what we want...

**Comment by samhatoum** [comment] 2016-06-27 14:50
it's not. We should ignore them for sure. You can set the screenshot path as a workaround in the config

**Comment by samhatoum** [comment] 2016-07-15 14:37
Duplicate of #197

**Closed by samhatoum** 2016-07-15 14:37 UTC
Labels: bug
