### ISSUE TITLE
browser.instances[0].waitUntil  throwing error.

### ISSUE THREAD

**Issue by JoeyAndres** [xolvio/chimp#214] opened 2015-12-29 04:54 UTC
In the old code (without multibrowser):

``` Javascript
browser.waitUntil(function() {
    console.log('asdf');
    return true;
}, 5000);
```

This executes perfectly well. But when I utilize multi-browser feature: 

``` Javascript
browser.instances[0].waitUntil(function() {
    console.log('asdf');
    return true;
}, 5000);
```

The inner block never gets executed. Wrapping it in a try catch block and printing error, I get:

`[Error: Can't wait without a fiber]`

I'm using this to wait for a url redirect basically. While this is being fixed, how do you wait for the current url equal the expected url.

**Comment by JoeyAndres** [comment] 2015-12-30 05:07
Now I'm getting
undefined: promise.then is not a function
        at World.global.user_should_be_in_session_page (features/sessions/support/helpers.js:12:27)

**Comment by samhatoum** [comment] 2015-12-30 13:49
are you using `.then` anywhere?

**Comment by samhatoum** [comment] 2015-12-30 13:49
the `multi-remote` branch is not fully tested until @lgandecki gets some time. Not sure if he can help here?

**Comment by lgandecki** [comment] 2015-12-30 14:34
Thanks for the feedback.

This is weird though. We do use waitUntil quite often with multibrowser functionality. This is a copy paste from our code:

```javascript
this.Given(/^([^ ]*) see "([^"]*)" label$/, function (person, label) {
        var _labelSelector = "//*[@id='iep_student_react']//label[text()='" + label + "']";
        getBrowserFor(person).waitUntil(function () {
            return this.isVisible(_labelSelector).then(function (visible) {
                return visible === true
            });
        });
        expect(getBrowserFor(person).isVisible(_labelSelector)).toBe(true);
});

function getBrowserFor(person) {
     return (person === 'Both') ? browser : browsers[person];
}
```

I set up the browsers in my first step:

```javascript
this.Given(/^There are two users$/, function () {
        browsers = {
            Alice: browser.instances[0],
            Bob: browser.instances[1]
        };
})
```
(the gherkin is a bit changed but that shouldn't matter)
```gherkin
 @focus
  Scenario: Login into the system
    Given There are two users
    When Both navigate to "/"
    Then Alice see "End Service" label
```
could you try and play around with this code to see whether this works for you? 
It does seem to do the same exact thing, but maybe you will discover something using similar pattern. 

Also, could you show me the: features/sessions/support/helpers.js:12:27 (with the context?)

**Comment by JoeyAndres** [comment] 2015-12-30 20:16
Ah, I should've posted my original code. Anywayz, in the master branch, I can do the following without a problem:

```javascript
get_browser_for(user).waitUntil(function() {
        var current_url = get_browser_for(user).url().value;
       return current_url === ROOT_URL + expected_url;
    });
```

But in the multidriver branch, those synchronous code (thanks to fibres), is not working inside waitUntil function, thus I have to use 

```javascript
get_browser_for(user).waitUntil(function() {
        return this.getUrl().then(function (url) {
            current_url = url;
            return current_url === ROOT_URL + expected_url;
        });
    });
```

**Comment by JoeyAndres** [comment] 2015-12-30 20:48
How you might wrap a this.server.call with a promise so I can place it in a waitUntil? This is the only problem left for me atm.

**Comment by lgandecki** [comment] 2016-01-04 15:18
So looks like the problem is that inside waitUntil we can't use sync code, I didn't even realize that my guys use a workaround for this, until you pointed that out in our code. :)
I will try to fix this in the next few days and will get back to you, thanks!

**Comment by lgandecki** [comment] 2016-11-18 21:38
I'd guess this is fixed by now. 
@JoeyAndres Are you still using chimp and can verify? :)

**Closed** 2018-07-12 16:18 UTC
