### ISSUE TITLE
Feature Request: ES2015 for Step Definitions

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#86] opened 2015-10-20 23:36 UTC
_From @workflow on October 12, 2015 20:32_

Could you (perhaps optionally) include the `ecmascript` package?

_Copied from original issue: xolvio/meteor-cucumber#227_

**Comment by samhatoum** [comment] 2015-10-20 23:36
Hey. The package won't work because chimp (and therefore cucumbers) run outside the meteor context in a separate node process.

I think it's a trivial add though, I will see about getting in the next version. Hopefully a week or so

**Comment by Temaruk** [comment] 2015-11-18 22:07
Cucumber supports the `--compiler` option since version `0.6.x` (see https://github.com/cucumber/cucumber-js/commit/dcdc32d72d97fd7edeaaf2a10dabc5d4f4398b59), which would let the usage of babel.js as a transpiler for step definitions (and other support files).

According to the babel.js docs (https://babeljs.io/docs/setup/#mocha) and the cucumber-js docs (https://github.com/cucumber/cucumber-js#transpilers) on the matter, passing the following along to cucumber would work: `--compiler js:babel-core/register`.

In theory, another possible solution could be to use a task runner (gulp/grunt) to first transpile step/support files, and then run chimp.

Maybe bumping cucumber-js from `^0.5.3` to at least `^0.6.0` (if not even higher, the latest is `0.9.1`, though I assume there could be breaking changes) could help?

**Comment by Temaruk** [comment] 2015-11-18 22:08
Forgot to add that another (temporary) solution would be what is suggested here: https://babeljs.io/docs/setup/#babel_register

**Comment by samhatoum** [comment] 2015-11-21 04:43
Just a small update: We're in the process of upgrading to the latest cucumber and making it easier to upgrade in the future using a cucumber-js fork

**Comment by SierraGolf** [comment] 2015-11-21 09:54
:+1:

**Comment by AdamBrodzinski** [comment] 2015-11-22 18:25
Nice, sounds great @samhatoum ! I'm really looking forward to using ES6 to dry up my code a bit!

**Comment by samhatoum** [comment] 2015-11-22 18:26
yea, us too :)

**Comment by kamek-pf** [comment] 2015-12-21 16:25
Any progress on this ? Chimp works great out of the box with Meteor, but ES6 would be a pretty nice addition :)

**Comment by samhatoum** [comment] 2015-12-21 16:38
yes, we hit a small roadblock with the cucumber upgrade and we're looking to resume that work soon

**Comment by samhatoum** [comment] 2015-12-21 16:38
will keep you posted here

**Comment by wirsingj** [comment] 2016-01-28 16:17
Hey-   I hit a road block while trying to implement the new Classes in ES6.   Just wondering if there is a any estimated timeframe for ES6 support.       I am going to look into the Babble transpiler until its fully supported.

Thanks!

**Comment by Sanjo** [comment] 2016-01-28 17:00
@wirsingj Very soon. In about one hour I will write you the instructions.

**Comment by Sanjo** [comment] 2016-01-28 17:13
1. Change the chimp version in package.json to `"chimp": "xolvio/chimp#dd5cb05",`
2. Install the new version of chimp `rm -r node_modules/chimp && npm install`
3. `npm install babel-register@^6.4.3` in your tests/cucumber folder or where your --path is set. As an alternative you can add the node_modules folder to the environment variable NODE_PATH. This is necessary for Cucumber to find the package.
4. Add your .babelrc config. In my case the content is:
```
{
  "presets": ["react", "es2015", "stage-0"],
  "plugins": ["transform-decorators-legacy"]
}
```
And the following npm packages:
```
  "babel-core": "^6.3.17",
  "babel-preset-es2015": "^6.3.13",
  "babel-preset-stage-0": "^6.3.13",
  "babel-preset-react": "^6.3.13",
  "babel-plugin-transform-decorators-legacy": "^1.2.0",
```
5.) Start chimp with the option: ` --compiler=js:babel-register`.

**Comment by wirsingj** [comment] 2016-01-28 17:45
I'll give that a shot-  Thanks for the quick response!

**Comment by wirsingj** [comment] 2016-01-28 21:36
For those instructions do you have chimp installed globally, or locally?    

If globally, where should I put my package.json?

Last question-  what did you mean in the second half of step 4?   (npm packages bit..)

**Comment by Sanjo** [comment] 2016-01-28 21:39
Create a package.json to your app, and add chimp and all the babel packages to the dev dependencies. Then do `npm install`.

**Comment by wirsingj** [comment] 2016-01-28 22:08
I set up my package.json (seemingly) correctly,  ran npm install  which made a node_modules folder..

but, when I try run chimp I get command not found...  

Any thoughts?


My package.json:
`{
  "name": "talos",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
  },
  "devDependencies": {
  "chimp": "xolvio/chimp#dd5cb05",
  "babel-register": "^6.4.3",
  "babel-core": "^6.3.17",
  "babel-preset-es2015": "^6.3.13",
  "babel-preset-stage-0": "^6.3.13",
  "babel-preset-react": "^6.3.13",
  "babel-plugin-transform-decorators-legacy": "^1.2.0"     
  },
  "scripts": {
    "test": "mocha"
  },
  "author": "",
  "license": "ISC"
}
`

**Comment by wirsingj** [comment] 2016-01-28 23:42
@Sanjo 
Update:
I can get Chimp to run using:  node node_modules/chimp/bin/chimp --watch --compiler=js:babel-register

Its still acting a bit weird though-   Where did you put your .babelrc config file?     Should it go in app/node_modules?

**Comment by Sanjo** [comment] 2016-01-29 00:32
@wirsingj You need to put the .babelrc directly into app/

**Comment by Sanjo** [comment] 2016-01-29 13:14
I have implemented a "ES2015 by default" feature: https://github.com/xolvio/chimp/tree/es2015-by-default. I think it makes sense, since Chimp wants to make it as easy as possible to get started.

**Comment by samhatoum** [comment] 2016-01-29 13:19
totally

**Comment by wirsingj** [comment] 2016-01-29 17:03
Fyi-  when I change the chimp version number to 9ba8e80 in my apps package.json and try to npm install I get this error now (Other build numbers seem to work though..):
`m ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! path /Users/jwirsing/git/Talos_Beta/node_modules/chimp/dist/bin/chimp.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/jwirsing/git/Talos_Beta/node_modules/chimp/dist/bin/chimp.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
`

**Comment by wirsingj** [comment] 2016-01-29 17:41
68b87b532e18c93884f0783099c7ecadb80f3fd0  is the last commit version in master that installs correctly.

**Comment by Sanjo** [comment] 2016-01-29 22:46
The current master branch has now ES2015 support by default. So no configurations are necessary.

**Comment by wirsingj** [comment] 2016-02-01 20:59
Hey-    The install is still failing..   I am trying to just do a plain   'npm install chimp' in my app folder, and its still complaining about a missing file...  This error only started happening after work began on the ES6 stuff:

npm install chimp      
talos@1.0.0 /Users/jwirsing/git/Talos_Beta
└── (empty)

npm WARN EPACKAGEJSON talos@1.0.0 No description
npm WARN EPACKAGEJSON talos@1.0.0 No repository field.
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "chimp"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! path /Users/jwirsing/git/Talos_Beta/node_modules/chimp/dist/bin/chimp.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/jwirsing/git/Talos_Beta/node_modules/chimp/dist/bin/chimp.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by Sanjo** [comment] 2016-02-02 03:01
@wirsingj Try to set the version to "xolvio/chimp#master".

**Comment by Sanjo** [comment] 2016-02-02 03:09
Oh, I see now what the problem is. I will fix it tomorrow.

Until then you can do:

```
git clone https://github.com/xolvio/chimp.git
cd chimp
npm install
npm link
```

And then in your project:

```
rm -rf node_modules/chimp
npm install chimp
```

This will use the local chimp version.

**Comment by wirsingj** [comment] 2016-02-03 21:51
I could not get the linking process to work..  I'll just wait until the fix is in place.

Thanks

**Comment by wirsingj** [comment] 2016-02-04 16:18
Seems there is still an issue with the file structure after pulling it from npm again.

`Error: Cannot find module '../dist/bin/chimp'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/jwirsing/git/Talos_Beta/node_modules/chimp/bin/chimp.js:3:1)`

When I compare the node_modules/chimp folders it looks like the /lib folder is missing-   and the chimp.js file in /bin is pointing to the wrong location for chimp.

**Comment by Sanjo** [comment] 2016-02-04 16:40
You can install it with the version v0.26.0-rc.0. Installing Chimp from GitHub is no longer supported, because we use ES2015 transpiling and don't want to commit the ./dist folder.

**Comment by wirsingj** [comment] 2016-02-04 17:31
Cool, thanks.

Running as it is throws:
[Error: Missing /Users/jwirsing/git/Talos_Beta/node_modules/selenium-standalone/.selenium/selenium-server/2.50.1-server.jar]

I changed the selenium install version number in /lib/selenium.js  to 2.50.1  and it seems to be working.

**Comment by Sanjo** [comment] 2016-02-05 03:54
ES2015 is now supported by default with 0.26.0.

**Closed by Sanjo** 2016-02-05 03:54 UTC
Labels: in progress

**Comment by workflow** [comment] 2016-02-08 10:15
:dart:
