### ISSUE TITLE
Failing installation of latest chimp@0.40.7 on windows 7

### ISSUE THREAD

**Issue by chiramelwin** [xolvio/chimp#475] opened 2016-09-21 05:31 UTC
Had an older version of chimp on updating to the latest version an error is reported which is entered in log output.

phantomjs2@2.2.0 is said to be unstable on their NPM page https://www.npmjs.com/package/phantomjs2

The following note is made on their page: phantomjs v2.x is currently under heavy development. Releases should be considered unstable.

#####  Used version
* Chimp: 0.40.7
* Node.js: v6.6.0
* Operation system: Windows

#####  Console / Log Output
npm WARN optional Skipping failed optional dependency /chimp/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "chimp"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs2@2.2.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs2@2.2.0 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\melwin\git\bddPartnerPortal\npm-debug.log
npm ERR! code 1
(Upload long logs to [Gist](https://gist.github.com/) and link it here)

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment] 2016-09-21 15:54
Please downgrade to Node 6.5.0 and try again

**Comment by chiramelwin** [comment] 2016-09-22 00:33
Hi thanks for you suggestion, I downgraded my node but I'm getting the following error when I run chimp for the first time.

Error: Cannot find module 'C'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Array.forEach (native)
    at Object.initializer (C:\Users\melwin\AppData\Roaming\npm\node_modules\chimp\node_modules\cucumber\lib\cucumber\cli\support_code_loader.js:22:25)
    at Object.Library (C:\Users\melwin\AppData\Roaming\npm\node_modules\chimp\node_modules\cucumber\lib\cucumber\support_code\library.js:120:25)
    at Object.getSupportCodeLibrary (C:\Users\melwin\AppData\Roaming\npm\node_modules\chimp\node_modules\cucumber\lib\cucumber\cli\support_code_loader.js:10:58)

    at Object.getSupportCodeLibrary (C:\Users\melwin\AppData\Roaming\npm\node_modules\chimp\node_modules\cucumber\lib\cucumber\cli\configuration.js:126:32)
    at Object.getSupportCodeLibrary (C:\Users\melwin\AppData\Roaming\npm\node_modules\chimp\node_modules\cucumber\lib\cucumber\runtime.js:43:46)
Cucumber steps failed
 
Chimp: 0.40.7
Node.js: v6.5.0
Operation system: Windows 7

**Comment by samhatoum** [comment] 2016-09-22 00:34
Duplicate of #432 (fix coming up)

**Closed by samhatoum** 2016-09-22 00:34 UTC

**Comment by samhatoum** [comment] 2016-09-22 00:43
Fixed in 0.41.0

**Comment by chiramelwin** [comment] 2016-09-22 00:52
Thanks issue is solved.
