### ISSUE TITLE
[chimp][helper] setupBrowserAndDDP had error

### ISSUE THREAD

**Issue by tlimpanont** [xolvio/chimp#496] opened 2016-10-14 08:22 UTC
> chimp --ddp=http://localhost:3000 --path=./app/tests/cucumber/features

```
[chimp] Running...
[chimp][helper] setupBrowserAndDDP had error
{ [Error: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"3267.1","isDefault":true},"id":1,"name":"","origin":"://"}]
  message: 'session not created exception\nfrom unknown error: Runtime.executionContextCreated has invalid \'context\': {"auxData":{"frameId":"3267.1","isDefault":true},"id":1,"name":"","origin":"://"}',
  type: 'RuntimeError',
  seleniumStack: 
   { status: 33,
     type: 'SessionNotCreatedException',
     message: 'A new session could not be created.',
     orgStatusMessage: 'session not created exception\nfrom unknown error: Runtime.executionContextCreated has invalid \'context\': {"auxData":{"frameId":"3267.1","isDefault":true},"id":1,"name":"","origin":"://"}\n  (Session info: chrome=54.0.2840.59)\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.11.6 x86_64) (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 720 milliseconds\nBuild info: version: \'2.50.1\', revision: \'d7fc91b\', time: \'2016-01-29 19:08:26\'\nSystem info: host: \'theuys-macbook-pro-2.local\', ip: \'192.168.178.17\', os.name: \'Mac OS X\', os.arch: \'x86_64\', os.version: \'10.11.6\', java.version: \'1.8.0_101\'\nDriver info: org.openqa.selenium.chrome.ChromeDriver' } }
Error: session not created exception
    at Object.Future.wait (/Users/theuylimpanont/Development/part-up/node_modules/fibers/future.js:449:15)
    at Object.<anonymous> (/Users/theuylimpanont/Development/part-up/node_modules/wdio-sync/build/index.js:345:27)
    at initBrowser (/Users/theuylimpanont/Development/part-up/node_modules/chimp/dist/lib/chimp-helper.js:168:17)
    at Object.setupBrowserAndDDP (/Users/theuylimpanont/Development/part-up/node_modules/chimp/dist/lib/chimp-helper.js:226:7)
    at /Users/theuylimpanont/Development/part-up/node_modules/chimp/dist/lib/cucumberjs/hooks.js:21:24
    at /Users/theuylimpanont/Development/part-up/node_modules/meteor-promise/fiber_pool.js:33:40
    - - - - -
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"3267.1","isDefault":true},"id":1,"name":"","origin":"://"}
    at new RuntimeError (/Users/theuylimpanont/Development/part-up/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:115:12)
    at Request._callback (/Users/theuylimpanont/Development/part-up/node_modules/webdriverio/build/lib/utils/RequestHandler.js:257:39)
    at Request.self.callback (/Users/theuylimpanont/Development/part-up/node_modules/webdriverio/node_modules/request/request.js:373:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/Users/theuylimpanont/Development/part-up/node_modules/webdriverio/node_modules/request/request.js:1318:14)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/Users/theuylimpanont/Development/part-up/node_modules/webdriverio/node_modules/request/request.js:1266:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by tlimpanont** [comment] 2016-10-14 13:15
@samhatoum @Sanjo

**Comment by lucetius** [comment] 2016-10-15 13:50
Please provide

#####  Used version

* Chimp: 
* Node.js:
* Operation system:

**Comment by samhatoum** [comment] 2016-10-15 23:39
@tlimpanont I'm closing this issue as you didn't follow any of the instructions that are present. Sorry to be mean, but you the rules are there to be read!

happy to help, but please take note of things that waste our time.

**Closed by samhatoum** 2016-10-15 23:39 UTC

**Comment by lnmunhoz** [comment] 2016-10-25 02:35
@samhatoum Please reopen this issue. I am having the same problem. But in my case I am trying to run `npm test` from the [qualityfaster](https://github.com/xolvio/qualityfaster/) repository. Chimp is working fine in other project.

- Chimp: 0.41.2
- Node: 4.6.1
- OS: Mac OSX El Capitan 10.11.6
- I have JDK installed

This is the error:
```
[chimp] Running...

[chimp] domain scenarios...
[chimp][helper] setupBrowserAndDDP had error
{ [Error: Connection refused (Connection refused)]
  message: 'Connection refused (Connection refused)',
  type: 'RuntimeError',
  seleniumStack:
   { status: 13,
     type: 'UnknownError',
     message: 'An unknown server-side error occurred while processing the command.',
     orgStatusMessage: 'Connection refused (Connection refused)' } }
Error: Connection refused (Connection refused)
    at Object.Future.wait (/Users/lnmunhoz/workspaces/playground/qualityfaster/.scripts/node_modules/fibers/future.js:449:15)
    at Object.<anonymous> (/Users/lnmunhoz/workspaces/playground/qualityfaster/.scripts/node_modules/wdio-sync/build/index.js:345:27)
    at initBrowser (/Users/lnmunhoz/workspaces/playground/qualityfaster/.scripts/node_modules/chimp/dist/lib/chimp-helper.js:125:15)
    at Object.setupBrowserAndDDP (/Users/lnmunhoz/workspaces/playground/qualityfaster/.scripts/node_modules/chimp/dist/lib/chimp-helper.js:200:7)
    at /Users/lnmunhoz/workspaces/playground/qualityfaster/.scripts/node_modules/chimp/dist/lib/cucumberjs/hooks.js:21:24
    at /Users/lnmunhoz/workspaces/playground/qualityfaster/.scripts/node_modules/meteor-promise/fiber_pool.js:33:40
    - - - - -
Cucumber steps failed
Chimp exited with code 2
Chimp exited with code 2
npm ERR! Test failed.  See above for more details.
```

**Comment by citricacid-pl** [comment] 2016-10-25 09:02
Hi,

Similar issue here. Removed node_modules for clean install.

- Chimp: 0.41.2
- Node: 6.8.1 (and 5.10.1)
- OS: macOS Sierra 10.12
- Java: 1.8.0_112 (brew)

**Comment by lgandecki** [comment] 2016-10-25 09:32
@lnmunhoz you have a different error:

{ [Error: session not created exception
vs
{ [Error: Connection refused (Connection refused)]

Nonetheless, I'm looking into it now. Will let you know.

@citricacid-pl could you please provide your console log? As you can see, it's easy to confuse different errors.

@tlimpanont I saw that before - I know that's a lame solution but restarting the OS helped in my case. Since it went away I couldn't reproduce and fix it. It might have something to do with stale selenium server.

**Comment by citricacid-pl** [comment] 2016-10-25 09:45
Sure @lgandecki 
There you go:

```
[chimp][helper] setupBrowserAndDDP had error
{ Error: session not created exception
    at Object.wait (/Users/citricacid/Workspace/application/tests/functional/node_modules/fibers/future.js:449:15)
    at Object.<anonymous> (/Users/citricacid/Workspace/application/tests/functional/node_modules/wdio-sync/build/index.js:345:27)
    at initBrowser (/Users/citricacid/Workspace/application/tests/functional/node_modules/chimp/dist/lib/chimp-helper.js:161:17)
    at Object.setupBrowserAndDDP (/Users/citricacid/Workspace/application/tests/functional/node_modules/chimp/dist/lib/chimp-helper.js:215:7)
    at /Users/citricacid/Workspace/application/tests/functional/node_modules/chimp/dist/lib/cucumberjs/hooks.js:21:24
    at /Users/citricacid/Workspace/application/tests/functional/node_modules/chimp/node_modules/meteor-promise/fiber_pool.js:32:39
    - - - - -
from unknown error: bad inspector message: {"method":"Page.loadEventFired","params":{"timestamp":2774,715723}}
  message: 'session not created exception\nfrom unknown error: bad inspector message: {"method":"Page.loadEventFired","params":{"timestamp":2774,715723}}',
  type: 'RuntimeError',
  seleniumStack:
   { status: 33,
     type: 'SessionNotCreatedException',
     message: 'A new session could not be created.',
     orgStatusMessage: 'session not created exception\nfrom unknown error: bad inspector message: {"method":"Page.loadEventFired","params":{"timestamp":2774,715723}}\n  (Session info: chrome=54.0.2840.71)\n  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.12.0 x86_64) (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 1.34 seconds\nBuild info: version: \'2.53.1\', revision: \'a36b8b1\', time: \'2016-06-30 17:37:03\'\nSystem info: host: \'macbook-air-piotr.local\', ip: \'192.168.1.4\', os.name: \'Mac OS X\', os.arch: \'x86_64\', os.version: \'10.12\', java.version: \'1.8.0_112\'\nDriver info: org.openqa.selenium.chrome.ChromeDriver' } }
Error: session not created exception
    at Object.wait (/Users/citricacid/Workspace/application/tests/functional/node_modules/fibers/future.js:449:15)
    at Object.<anonymous> (/Users/citricacid/Workspace/application/tests/functional/node_modules/wdio-sync/build/index.js:345:27)
    at initBrowser (/Users/citricacid/Workspace/application/tests/functional/node_modules/chimp/dist/lib/chimp-helper.js:161:17)
    at Object.setupBrowserAndDDP (/Users/citricacid/Workspace/application/tests/functional/node_modules/chimp/dist/lib/chimp-helper.js:215:7)
    at /Users/citricacid/Workspace/application/tests/functional/node_modules/chimp/dist/lib/cucumberjs/hooks.js:21:24
    at /Users/citricacid/Workspace/application/tests/functional/node_modules/chimp/node_modules/meteor-promise/fiber_pool.js:32:39
    - - - - -
from unknown error: bad inspector message: {"method":"Page.loadEventFired","params":{"timestamp":2774,715723}}
```

**Comment by lnmunhoz** [comment] 2016-10-25 09:53
@lgandecki I reinstalled my JDK and now I am having the same error as @citricacid-pl.

**Comment by citricacid-pl** [comment] 2016-10-25 09:54
Restarting OS didn't help here this time ;)

**Comment by lgandecki** [comment] 2016-10-25 10:02
Cool! thanks for the update guys! I actually did just reproduce this on the qualityfaster repo, so it should be much easier to fix it now! :)

**Comment by lgandecki** [comment] 2016-10-25 12:19
@citricacid-pl could you show me what command you use to run chimp? and if you use chimp.js file, that also?

**Comment by citricacid-pl** [comment] 2016-10-25 13:06
Sure.

Excerpt of package.json

```
"scripts": {
    "test": "chimp",
    "watch": "chimp --watch",
    "ci": "chimp --browser=phantomjs --screenshotsOnError=true"
  }
```

And I am running it with `npm test`

**Comment by lgandecki** [comment] 2016-10-25 13:43
@citricacid-pl could you please double check the version inside your node_modules and the global one? 
./node_modules/.bin/chimp --version
`which chimp` --version

**Comment by lgandecki** [comment] 2016-10-25 13:45
@citricacid-pl oh, ok, you have the problem where you need to do export LC_NUMERIC=en_US.UTF-8 before running your chimp...


"scripts": {
    "test": "LC_NUMERIC=en_US.UTF-8 chimp",
    "watch": "LC_NUMERIC=en_US.UTF-8 chimp --watch",
    "ci": "LC_NUMERIC=en_US.UTF-8 chimp --browser=phantomjs --screenshotsOnError=true"
  }

try this please

**Comment by citricacid-pl** [comment] 2016-10-25 13:45
I have no global.

```
15:45 $ ./node_modules/.bin/chimp --version
0.41.2
```

**Comment by lgandecki** [comment] 2016-10-25 13:47
@lnmunhoz the problem with quality faster is that it uses an old version of chimp. You probably checked the globally installed version. We will get to upgrade that shortly, but that's not the highest priority right now.
Chimp does work fork your actual project, right?

**Comment by citricacid-pl** [comment] 2016-10-25 13:47
@lgandecki Solved with LC_NUMERIC=en_US.UTF-8 

Thanks a lot.

What is the problem exactly?

**Comment by lgandecki** [comment] 2016-10-25 13:54
There is some weirdness in the newest chrome...
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1552
in your log we can see that chrome returns a timestamp {"timestamp":2774,715723}}
which brakes Selenium, looks like. (it's the , instead of . - which is based on your LC_NUMERIC)

Not sure how to deal with that in chimp yet.

**Comment by citricacid-pl** [comment] 2016-10-25 13:57
Dzięki bardzo.

**Comment by lgandecki** [comment] 2016-10-25 14:06
;-)

**Comment by lnmunhoz** [comment] 2016-10-25 21:39
@lgandecki Works in my project but I am trying to understand de CI process to implement in my projects and I want to run the qualityfaster project to study purposes.

There's some way to update the chimp from qualityfaster by my own?

**Comment by lnmunhoz** [comment] 2016-10-25 22:06
@lgandecki Worked like a charm! I updated chimp version from `./scripts/package.json` to `0.41.1`.

Nott all the tests passed, but I think now its just code to fix:
```
 Scenario: Account has insufficient funds
  ✔ Given I have an account with the branch number 12345
  ✔ And "James" has an account with the branch number 12345
  ✔ Given my bank account balance is $10
  ✔ And "James"'s bank account balance is $50
  ✔ When I transfer $20 to "James"'s bank account
  ✖ Then I should be informed there are insufficient funds
  - And my account balance should be $10
  - And "James"'s account balance should be $50

Failures:

1) Scenario: Account has insufficient funds - tests/specifications/transfers/same-bank-money-transfers.feature:19
   Step: Then I should be informed there are insufficient funds - tests/specifications/transfers/same-bank-money-transfers.feature:23
   Step Definition: funds.js:2
   Message:
     ExpectationFailed: Expected undefined to equal Object({ message: 'Insufficient Funds' }).
         at World.<anonymous> (step_definitions/critical/Then I should be informed there are insufficient funds.js:3:37)

3 scenarios (1 failed, 2 passed)
25 steps (1 failed, 2 skipped, 22 passed)
0m07.569s

Cucumber steps failed
Chimp exited with code 2
Chimp exited with code 2
npm ERR! Test failed.  See above for more details.
```

**Comment by lgandecki** [comment] 2016-10-26 09:18
Yup. Happy to know it works now. Those are definitely just test code fixes. 
Please let us know if you need help setting up the CI.

**Comment by lnmunhoz** [comment] 2016-10-26 11:47
@lgandecki Thank you!

**Comment by joelmeiller** [comment] 2016-10-28 15:27
Had the same problem and the update to 0.41.1 helped :) Thanks a lot!

**Comment by andrialexandrou** [comment] 2016-10-28 19:39
I'm running node v6.6.0, chimp v0.41.2 (w/ cucumber v1.3.0) and still getting a `pending is not defined`, but what confuses me is I have 2 Before hooks, yet it's only the `@bug` hook that errors. 
```
	this.Before( "@pending", function() {
		// We use this to indicate that automation code is still being written
		pending();
	} );

	this.Before( "@bug", function() {
		// We use this to indicate a current bug in the UI that won't be corrected for a while
		pending();
	} );
```
I followed this thread, which got rid of most of my problems, namely by bumping up the version and delivering the LC_NUMERIC env var before running. Hoping I'm missing something obvious.

**Comment by jperasmus** [comment] 2016-11-01 11:16
I get the same as @andrialexandrou with one exception, I have node v6.7.0.

**Comment by lgandecki** [comment] 2016-11-01 19:24
@andrialexandrou @jperasmus hey guys, thanks for letting us know. This issue is closed and doesn't seem related to your problem Could you open a separate issue?
Thanks a lot!

**Comment by andrialexandrou** [comment] 2016-11-01 21:23
#522 Thanks -- just opened the issue as #522.

**Comment by feitla** [comment] 2016-11-18 19:13
@samhatou  you closed the issue after giving the guy 1 day to respond? 1 day is wasting your time?

**Comment by thebarty** [comment] 2016-11-20 06:37
just letting your guys know that for me ``LC_NUMERIC=en_US.UTF-8 chimp ...`` did the trick. Weird stuff. Thanks for your help!
